#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true


bspc rule -a discord desktop="^9"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off



[ -z "$(pgrep -f dunst)" ] && dunst &
[ -z "$(pgrep -f picom)" ] && sleep 1s && picom --experimental-backend &
[ -z "$(pgrep -f flashfocus)" ] &&  sleep 1s && flashfocus &
