#!/usr/bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep bspswallow || bspswallow &

#bspc monitor -d I II III IV V VI VII VIII IX X

bspc monitor DisplayPort-0 -d 1 2 3 4 5
bspc monitor HDMI-A-0 -d 6 7 8 9 0

#bspc monitor DisplayPort-0 -d 1 3 5 7 9
#bspc monitor HDMI-A-0 -d 2 4 6 8 0

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#bspc config focus_follows_pointer true


#bspc config pointer_follows_focus true

bspc config pointer_modifier mod1
bspc config pointer_action1 move

bspc rule -a discord desktop="^9"
# fix
bspc rule -a Spotify desktop="^10"
bspc rule -a mpv state=fullscreen

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
# floating rules taken from: github.com/archcraft-os/archcraft-bspwm/blob/main/files/bspwmrc

declare -a floating=(st-float 'firefox:Toolkit' \
    Viewnior Gpicview feh Lxappearance Galculator)
for i in ${floating[@]}; do
    bspc rule -a $i state=floating follow=on focus=on;
done


autostart.sh &
