#!/usr/bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep bspswallow || bspswallow &

#bspc monitor -d I II III IV V VI VII VIII IX X

bspc monitor DisplayPort-0 -d 1 2 3
bspc monitor HDMI-A-0 -d 4 5 6 7 8 9 0


bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#bspc config focus_follows_pointer true


#bspc config pointer_follows_focus true

bspc config pointer_modifier mod1
bspc config pointer_action1 move

bspc rule -a discord desktop="^9"
bspc rule -a mpv state=floating

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled

# floating rules taken from: github.com/archcraft-os/archcraft-bspwm/blob/main/files/bspwmrc
declare -a floating=(st-float 'firefox:Toolkit' \
    Viewnior Gpicview feh Lxappearance Galculator Peek)
for i in ${floating[@]}; do
    bspc rule -a $i state=floating follow=on focus=on;
done


#autostart.sh &
#pkill -f picom || picom --experimental-backend &
#pkill -f picom || picom &
#pkill -f flashfocus || flashfocus &
